repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  #- id: check-yaml  # This doesn't work for me (2023-06-06)
  - id: end-of-file-fixer
    exclude: \.txt$
  - id: trailing-whitespace                # Remove trailing whitespaces
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: detect-private-key
  - id: sort-simple-yaml
        # Fix common spelling mistakes
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: []
    types_or: [rust, markdown]
    #files: ^(src||tests)/

# - repo: https://github.com/lovesegfault/beautysh
#   rev: v6.2.1
#   hooks:
#   - id: beautysh

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: v1.3.0
  hooks:
  - id: nixpkgs-fmt
