[package]
name = "rsgpr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "*"
ndarray-stats = "*"
utm = "*"
chrono = "*"
nshare = "*"
#show-image = "*"
image = "*"
ndarray-linalg = {version = "0.13", features = ["openblas-static"]}
smartcore = "*"
noisy_float = "*"
rayon = "*"
